// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgxPUvuPE6ZzzSporahYwviu3tZAR1APw',
    appId: '1:281857439154:web:7a67c3c774c0c1c0f920ab',
    messagingSenderId: '281857439154',
    projectId: 'phamngocthanginfo',
    authDomain: 'phamngocthanginfo.firebaseapp.com',
    storageBucket: 'phamngocthanginfo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_1a2foDhgD5yX6AA26H7Jd7aHz3_PQz0',
    appId: '1:281857439154:android:5e7e62d0735a0a3ef920ab',
    messagingSenderId: '281857439154',
    projectId: 'phamngocthanginfo',
    storageBucket: 'phamngocthanginfo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6aWY0bH3iGY-cgERDErm7Bm0pgweG9hU',
    appId: '1:281857439154:ios:2b857ea17d167d3ff920ab',
    messagingSenderId: '281857439154',
    projectId: 'phamngocthanginfo',
    storageBucket: 'phamngocthanginfo.appspot.com',
    iosClientId: '281857439154-p6hjn71bfe2ko52t2ldqftiaeff3opd4.apps.googleusercontent.com',
    iosBundleId: 'pham.ngoc.thang.myProfile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6aWY0bH3iGY-cgERDErm7Bm0pgweG9hU',
    appId: '1:281857439154:ios:2b857ea17d167d3ff920ab',
    messagingSenderId: '281857439154',
    projectId: 'phamngocthanginfo',
    storageBucket: 'phamngocthanginfo.appspot.com',
    iosClientId: '281857439154-p6hjn71bfe2ko52t2ldqftiaeff3opd4.apps.googleusercontent.com',
    iosBundleId: 'pham.ngoc.thang.myProfile',
  );
}
