// ignore_for_file: avoid_print
import 'dart:convert';
import 'dart:io';

void main() async {
  try {
    print('Generating dynamic build version information...');
    
    // Run flutter --version --machine
    final result = await Process.run('flutter', ['--version', '--machine']);
    if (result.exitCode != 0) {
      throw Exception('Flutter command failed: ${result.stderr}');
    }
    
    final data = jsonDecode(result.stdout as String);
    final flutterVersion = data['frameworkVersion'] ?? '3.41.9';
    final dartVersion = data['dartSdkVersion'] ?? '3.11.5';
    
    // Read version from pubspec.yaml
    final pubspecFile = File('pubspec.yaml');
    String appVersion = '1.0.0+1';
    if (await pubspecFile.exists()) {
      final lines = await pubspecFile.readAsLines();
      for (final line in lines) {
        if (line.startsWith('version:')) {
          appVersion = line.replaceFirst('version:', '').trim();
          break;
        }
      }
    }
    
    // Generate lib/core/build_version.dart
    final outputFile = File('lib/core/build_version.dart');
    final content = '''// Generated by tool/generate_version.dart. Do not edit manually.
class BuildVersion {
  static const String flutterVersion = '$flutterVersion';
  static const String dartVersion = '$dartVersion';
  static const String appVersion = '$appVersion';
  static const String buildTime = '${DateTime.now().toUtc().toIso8601String()}';
}
''';
    
    await outputFile.writeAsString(content);
    print('Successfully generated lib/core/build_version.dart:');
    print('  Flutter: $flutterVersion');
    print('  Dart: $dartVersion');
    print('  App: $appVersion');
  } catch (e) {
    print('Error generating build version: $e');
    exit(1);
  }
}
