// Generated by tool/generate_version.dart. Do not edit manually.
class BuildVersion {
  static const String flutterVersion = '3.41.9';
  static const String dartVersion = '3.11.5';
  static const String appVersion = '1.0.0+1';
  static const String buildTime = '2026-06-01T17:02:12.810459Z';
}
